### ISSUE TITLE
can't stake

### ISSUE THREAD

**Issue by knauto** [Wonderland-Money/wonderland-frontend#53]
{"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"code":-32000,"message":"execution reverted"},"method":"estimateGas","transaction":{"from":"0x90f87dc29d7B2F747eF0C27647F954E26bd6f76f","gasPrice":{"type":"BigNumber","hex":"0x06fc23ac00"},"to":"0x096BBfB78311227b805c968b070a81D358c13379","data":"0x7acb77570000000000000000000000000000000000000000000000000000000077586a1a00000000000000000000000090f87dc29d7b2f747ef0c27647f954e26bd6f76f","accessList":null}}
I've tried different prices with no luck. I manually put price in and I've tried clicking MAX and I still get Sumthing went wrong error.
Windows 10 up to date
Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**To Reproduce**

**Expected behavior**

**Workarounds (if any)**
Is there an option to get around this bug to the intended action?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nwoodr94** [comment]
Hi @knauto, I posted [another comment](https://github.com/Wonderland-Money/wonderland-frontend/issues/50#issuecomment-991780674) on a related issue but it's looking like you might have a slightly different gas fee/transaction issue related to either metamask or the smart contract in general.

Take a look at this [blog article](https://www.followchain.org/cannot-estimate-gas-pancakeswap/). Can you report back and say whether the decimal places or slippage corrections resolve your issue? In this case it would help us develop more specific error messages explaining what the problem is.

I dont't think the slippage should be a problem since we're on the AVAX network, but if you're only able to resolve the problem by, for example, only staking 2 TIME, rather than your full 2.0022 TIME, this would be a good candidate issue for the [contract developers](https://github.com/Wonderland-Money/contracts) to look into.

**Comment by s1k2614** [comment]
Hey knauto, I think you don't have enough AVAX in your wallet to pay the fee. When you stake the first time, there is a small fee and also when you stake several times. I made the same mistake, so make sure when you swap your AVAX to TIME that you leave about 0,02-0,015 AVAX in the connected wallet to wonderland, so you can cover gas fees.
I "fixed" that by sending a little bit more AVAX to said wallet. Because it seems to be the same problem here.

**Comment by DeanieBriz** [comment]
I am getting the following red error message when trying to stake time in wonderland time. "Execution Reverted" What could it be?

**Comment by PEDRO00751** [comment]
EXECUTION REVERTED: what is it?
OS: Windows 10E
MS Edge Version 96.0.1054.62 (Official build) (64-bit)
TRYING TO STAKE 0,566 TIME 
{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32000,
    "message": "execution reverted"
  },
  "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"
}
