### ISSUE TITLE
 JSON-RPC error

### ISSUE THREAD

**Issue by bigstott** [Wonderland-Money/wonderland-frontend#74]
**Describe the bug**
I get an error message when trying to stake time. I already have a little in there but wanted to add more. The error i get is

{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"}
![Screenshot 2022-01-15 075749](https://user-images.githubusercontent.com/94342755/149626359-1508acbb-b1e4-4403-a6d6-c27617ce63d6.jpg)

This happens on my phone AND on my PC browser.

I should be able to just stake normally.

**Comment by bbrannon29** [comment]
I am getting the same thing on mobile and pc. I unstaked what I had in hopes that re-staking the total amount would resolve the issue. But it did not, still unable to stake TIME.

**Comment by TheMarovian** [comment]
Wondering if this issue has been resolved with the wMEMO updates or not? If not I can take a closer look to see if there's any way I could help.

P.S. Not one of the devs on Wonderland, so wont be able to help out as much as they would.
