### ISSUE TITLE
Is anyone able to stake?????

### ISSUE THREAD

**Issue by thefutureofxaq** [Wonderland-Money/wonderland-frontend#78]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Workarounds (if any)**
Is there an option to get around this bug to the intended action?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by verbatim1** [comment]
Hi, I also can't stake.
Go to https://app.wonderland.money/#/stake
Metamask connected, Avax network
Amount in Time correctly visualised
Click on Max, Stake Time
Error reported: execution reverted, {"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"}

Windows 11 Home Single Language
Google Chrome
Versión 97.0.4692.71 (Build oficial) (64 bits)

Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
RAM 8,00 GB (7,88 GB usable)

Can some help?

Thanks

**Comment by linocatucci** [comment]
Hello I can't stake aswel. 

this morning (Jan-18-2022 08:03:48 AM +UTC) I have tried to stake my Time amount but it does not show up as MEMO in my metamask. Also the amount of Time is still the same.
When I look at the snowtrace.io , I see that the stake transaction is Success full. AVAX Transaction Hash (Txhash) Details | SnowTrace
When in connect with my metamask to Wonderland I don’t see any staked MEMO and the amount of Time is still the same.

When I try to stake again, I am getting an error message:

{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n \"code\": -32603,\n \"message\": \"Internal JSON-RPC error.\",\n \"data\": {\n \"code\": -32000,\n \"message\": \"execution reverted\"\n },\n \"stack\": \"Error: Internal JSON-RPC error.\\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"}

**Comment by Mary-dev-a** [comment]
Hello @linocatucci @verbatim1 @thefutureofxaq Kindly chat with one of the dev on live chat to get a quicker response [click here](https://www.wonderland.support)
